# This file is autogenerated by FoxBuild.
PROJECT_NAME="SDM660"
PROJECT_ARTIFACT="android_kernel_sdm660"
PROJECT_VERSION="6.0"

PROJECT_PATH="/home/leona/Desktop/FoxBuild/SDM660"

repos() {
    warning " Clonning '$PROJECT_ARTIFACT'..."
    git clone https://github.com/OpenFoxLab/android_kernel_sdm660.git

    cd $PWD/$PROJECT_ARTIFACT
    git clone https://github.com/OpenFoxLab/android_aarch64_toolchain.git

    info " Kernel ready to be built."
}

onBuild() {
    cd $PWD/$PROJECT_ARTIFACT
    info "==========================="
    info "|         BUILDING        |"
    info "==========================="

    source $PWD/build_kernel.sh
    build

    mkdir $PWD/../../../binaries
    cp out/arch/arm64/boot/Image $PWD/../../../binaries/Image

    cd ../

    info "==========================="
    info "|         FINISHED        |"
    info "==========================="
}

onClean() {
    cd $PWD/$PROJECT_ARTIFACT

    info " -> Removing '/arch/arm64/boot' folder..."
    rm -rf $PWD/arch/arm64/boot

    info " -> Removing '/out' folder..."
    rm -rf $PWD/out

    info " -> Removing build data..."
    make mrproper

    info " -> Cleaning folders..."
    make clean

    info " -> Cleaning finished."
    cd ../
}
