# This file is autogenerated by FoxBuild.
PROJECT_NAME="G990B"
PROJECT_ARTIFACT="G990B"
PROJECT_VERSION="1.0.0"

PROJECT_PATH="/c/Users/vakea/OneDrive/Desktop/FoxBuild/G990B"

ARCH=arm64

BUILD_CROSS_COMPILE=$PROJECT_PATH/toolchains/aarch64/bin/aarch64-linux-android-
KERNEL_LLVM_BIN=$PROJECT_PATH/toolchains/llvm-arm/10.0.9/bin/clang
CLANG_TRIPLE=$PROJECT_PATH/toolchains/aarch-linux/13.0/bin/aarch64-linux-gnu-
KERNEL_MAKE_ENV="CONFIG_BUILD_ARM64_DT_OVERLAY=y"

repos() {
    echo "Downloading toolchains..."

    mkdir $PROJECT_PATH/toolchains
    git clone https://github.com/OpenFoxLab/android_aarch64_toolchain $PROJECT_PATH/toolchains/aarch64
    git clone https://github.com/xiangfeidexiaohuo/Snapdragon-LLVM.git $PROJECT_PATH/toolchains/llvm-arm/10.0.9
    git clone https://github.com/radcolor/aarch64-linux-gnu $PROJECT_PATH/toolchains/aarch-linux/13.0

    echo "Downloading SM-G990B kernel srcs..."

    mkdir $PROJECT_PATH/src
    git clone https://github.com/OpenFoxLab/android_kernel_SM-G990B $PROJECT_PATH/src
    echo "Download completed."
}

onBuild() {
    mkdir $PROJECT_PATH/dists
    echo "Building kernel..."

    cd $PROJECT_PATH/src
    mkdir out

    make -j64 -C $(pwd) O=$PROJECT_PATH/dists $KERNEL_MAKE_ENV ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE CONFIG_SECTION_MISMATCH_WARN_ONLY=y vendor/papaya_r9q_defconfig
    make -j64 -C $(pwd) O=$PROJECT_PATH/dists $KERNEL_MAKE_ENV ARCH=$ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE CONFIG_SECTION_MISMATCH_WARN_ONLY=y

    echo "Exporting compiled kernel to '$PROJECT_PATH/dists'"
    cp out/arch/arm64/boot/Image $PROJECT_PATH/dists/G990B/Image

    echo "Build finished."
}

onClean() {
    echo "Clearing out build files..."

    rm -rf $PROJECT_PATH/dists
    rm -rm $PROJECT_PATH/src/out
    make clean
    make mrproper

    echo "Cleaning completed."
}
