#!/bin/bash

COMMAND_NAME="init"
COMMAND_USAGE="<name> <version> <artifact>"
COMMAND_DESCRIPTIONS="To setup the environement"

execute() {
    if [ ! -z $1 ]; then
        if [ ! -z $2 ]; then
            if [ ! -z $3 ]; then
                if [ -d "$(pwd)/$1" ]; then
                    echo -e " \033[1;35m->\033[1;0m \033[1;31m$1 Already created.\033[1;0m"
                    exit 0
                fi

                mkdir $1
                cd $(pwd)/$1
                makeBuild "$1" "$2" "$3"
                cd ../
                source $(pwd)/$1/build.sh
                echo -e " \033[1;35m->\033[1;0m \033[1;33mProject created:\033[1;0m"
                echo -e "  \033[1;35m->\033[1;0m \033[1;33mName: $PROJECT_NAME\033[1;0m"
                echo -e "  \033[1;35m->\033[1;0m \033[1;33mVersion: $PROJECT_VERSION\033[1;0m"
                echo -e "  \033[1;35m->\033[1;0m \033[1;33mArtifact: $PROJECT_ARTIFACT\033[1;0m"
                exit 0
            fi
        fi
    fi
}

makeBuild () {
cat <<EOF > build.sh
# This file is autogenerated by FoxBuild.
PROJECT_NAME="$1"
PROJECT_ARTIFACT="$3"
PROJECT_VERSION="$2"

PROJECT_PATH="$(pwd)"

repos() {
    #
    # Add the repos.
    #
}

onBuild() {
    #
    # Build process event.
    #
}

onClean() {
    #
    # Clean process event.
    #
}
EOF
}
